## Chapter 5: Dimensionality reduction techniques

```{r}
date()
```

Here we go again...

Remember! Set your working directory and load your libraries.

```{r setup5, message=FALSE}

knitr::opts_knit$set(root.dir ="C:/Users/ramosgon/OneDrive - University of Helsinki/Courses/OpenDataScience/IODS-project/Data")

library(tidyverse)
library(car)
library(GGally)
library(FactoMineR)

```

We read the data.

```{r}

human <- read.csv("human_base.csv", header = T, sep = ",")

```

```{r}

human$GNI <- human$GNI %>%
  gsub(",","", x = .) %>%
  as.numeric

```

```{r}

keep <- c("Country", "Edu2.FM", "Labo.FM", "Edu.Exp", "Life.Exp",
          "GNI", "Mat.Mor", "Ado.Birth", "Parli.F")

human <- human %>%
  select(one_of(keep))

human_ <- human %>% 
  filter(complete.cases(human))

```

```{r}

tail(human_, 10)

last <- nrow(human_) - 7

human_ <- human_[1:last, ]

rownames(human_) <- human_$Country

human <- human_[,-1]

```

```{r}

dim(human)

str(human)

summary(human)

```

```{r}

human %>% rownames_to_column(var = "Country") %>%
  pivot_longer(cols = c(-1), names_to = "Attribute", values_to = "Value") %>%
  ggplot(aes(x = Attribute, y = Value)) +
  geom_boxplot() +
  facet_wrap("Attribute", scales = "free", nrow = 2) +
  theme_classic()

```

```{r}

colnames(human) %>% sapply(function(x){
  qqPlot(human[,x], main = x)
})

```

```{r}

human %>%
  ggpairs(mapping = aes(alpha = 0.3))

human %>%
  ggcorr(method = c("everything", "pearson"))

```

```{r}

pca_human <- prcomp(human)

s <- summary(pca_human)
s

```

```{r,fig.height=15, fig.width=15}

pca_pr <- round(100*s$importance[2,], digits = 2) 

biplot(pca_human, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

```

```{r}

human_std <- scale(human)

pca_human <- prcomp(human_std)

s <- summary(pca_human)
s

```

```{r,fig.height=15, fig.width=15}

pca_pr <- round(100*s$importance[2,], digits = 2) 

biplot(pca_human, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

```

```{r}

data(tea)

dim(tea)

str(tea)

summary(tea)

```

```{r, fig.height=15, fig.width=10}

tea %>%
  select(-age) %>%
  pivot_longer(cols = c(-sex), names_to = "Attribute", values_to = "Value") %>%
  ggplot(aes(Value, fill = sex)) +
  facet_wrap("Attribute", scales = "free") +
  geom_bar(position = "dodge",alpha = 0.4) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))

```

```{r}

mca <- tea %>%
  select(-age) %>% 
  MCA(graph = FALSE)

summary(mca)

```

```{r, fig.height=15, fig.width=15}

plot(mca, invisible=c("ind"), habillage = "quali")

```
